const $=s=>document.querySelector(s),weaponAssetPaths=['assets/weapons/bone_sprayer.png','assets/weapons/corpse_burner.png','assets/weapons/crying_hedgehog.png'];
// Environment slots mirror TEXTURE_FILES in src/environment.js: every slot renders procedurally in game
// until its PNG lands, so this panel reports which ones are still running on the fallback drawing.
const environmentSlots=[['ground','Yard ground'],['asphalt','Road surface'],['fence','Boundary fence'],['house_left','Neighbour facade · left'],['house_right','Neighbour facade · right'],['house_top','Neighbour facade · north'],['house_bottom','Neighbour facade · south'],['streetlamp','Streetlamp'],['shelter','Player shelter'],['barricade','Wooden barricade'],['debris','Rubble / wreck'],['trap','Gutter trap']];
const environmentAssetPaths=environmentSlots.map(([key])=>`assets/environment/${key}.png`);
// Destructible props are one slot per kind AND per damage state, because each state is its own photograph:
// a burst barrel is not a tinted intact barrel. The names mirror textureSlots in src/destructibles.js, so
// this panel cannot drift away from what the renderer actually asks for.
const propKindLabels=[['car','Wrecked car'],['barrel','Fuel barrel'],['crate','Supply crate'],['fence','Yard fence'],['lamp','Streetlamp post']];
const propStateLabels=[['intact','Intact'],['damaged','Damaged'],['ruined','Ruined']];
const destructibleSlots=propKindLabels.flatMap(([kind,kindLabel])=>propStateLabels.map(([state,stateLabel])=>[`${kind}_${state}`,`${kindLabel} · ${stateLabel}`]));
const destructibleAssetPaths=destructibleSlots.map(([key])=>`assets/environment/destructibles/${key}.png`);
async function init(){if(window.QC||await new Promise(r=>{const end=Date.now()+2000,t=setInterval(()=>{if(window.QC||Date.now()>end){clearInterval(t);r(window.QC)}},20)})){await QC.ready();await QC.style.applyMainCss();await Promise.all(['data/weapons/weapons.json','data/components/components.json','assets/characters/survivor_sheet.png',...weaponAssetPaths,...environmentAssetPaths,...destructibleAssetPaths].map(path=>QC.fs.watchFile(path,()=>loadData())))}document.getElementById('__qc-fouc-guard')?.remove();bindAssetActions();await loadData()}function ask(prompt){if(!window.QC)return;new QC.forms.AgentRequestPopup({root:$('#agent-slot'),agent_name:'Cody',prompt}).open()}function bindAssetActions(){$('#open-survivor').onclick=()=>window.QC&&QC.ui.openFile('assets/characters/survivor_sheet.png');$('#open-screen').onclick=()=>window.QC&&QC.ui.openFile('assets/style/first_night_screen.png');$('#regen-survivor').onclick=async()=>{if(!window.QC)return;const ok=await QC.actions.regenerateSection('files.assets.characters.survivor_sheet_png');if(ok)$('#survivor-preview').src='/assets/characters/survivor_sheet.png?t='+Date.now()};$('#convert-webp').onclick=()=>ask('Use the webp_to_sprite_grid skill on an animated WebP selected by the user. Required settings: STRENGTH 100, SKIP_GENERATION True, MAKE_TRANSPARENT rembg. Save the resulting game-ready sprite grid under assets/characters/ and document its frame geometry.');$('#convert-video').onclick=()=>ask('Use gamedev_convert_video_to_sprite_sheet on a short source video selected by the user. Remove the background, preserve alpha, use stable autocrop, output 128x128 tiles under assets/characters/, and wire the result into the browser Canvas prototype.');$('#edit-assets').onclick=()=>ask('Continue the First Night vertical slice from meta/plans/weapon-lab-mvp.md. Improve the live asset pipeline and keep all player-facing content in English.')}async function json(path){const r=await fetch(`${path}?t=${Date.now()}`);if(!r.ok)throw new Error(`Cannot load ${path}`);return r.json()}// Renders one card per environment slot. The badge flips to PLACEHOLDER when the PNG is absent, which is
// exactly the moment the game silently falls back to its procedural drawing for that element.
function renderEnvironment(stamp){$('#environment').innerHTML=environmentSlots.map(([key,label])=>`<article class="card"><div class="weapon-preview"><img src="/assets/environment/${key}.png?t=${stamp}" alt="${label} texture"><div class="weapon-fallback"><b>${label}</b><span>Procedural fallback active</span></div><span class="asset-state status-teal">TEXTURE READY</span></div><div class="row"><h3>${label}</h3><code>${key}</code></div><div class="toolbar"><button class="button-small open" data-file="assets/environment/${key}.png">Open Texture</button></div></article>`).join('')}
// One card per prop state. Same badge contract as the environment panel: PLACEHOLDER means the game is
// drawing that state procedurally, which is a visible style break now that its neighbours are photographs.
function renderDestructibles(stamp){$('#destructibles').innerHTML=destructibleSlots.map(([key,label])=>`<article class="card"><div class="weapon-preview"><img src="/assets/environment/destructibles/${key}.png?t=${stamp}" alt="${label} texture"><div class="weapon-fallback"><b>${label}</b><span>Procedural fallback active</span></div><span class="asset-state status-teal">TEXTURE READY</span></div><div class="row"><h3>${label}</h3><code>${key}</code></div><div class="toolbar"><button class="button-small open" data-file="assets/environment/destructibles/${key}.png">Open Texture</button></div></article>`).join('')}
async function loadData(){try{const [wd,cd]=await Promise.all([json('/data/weapons/weapons.json'),json('/data/components/components.json')]);const stamp=Date.now();renderEnvironment(stamp);renderDestructibles(stamp);$('#weapons').innerHTML=wd.weapons.map(w=>`<article class="card"><div class="weapon-preview"><img src="/assets/weapons/${w.id}.png?t=${stamp}" alt="${w.display_name} texture"><div class="weapon-fallback"><b>${w.display_name}</b><span>Procedural game fallback active</span></div><span class="asset-state status-teal">TEXTURE READY</span></div><div class="row"><h3>${w.display_name}</h3><code>${w.id}</code></div><p>${w.description}</p><div class="stat"><span>Role</span><b>${w.role}</b></div><div class="stat"><span>Damage</span><b>${w.base.damage} × ${w.base.projectiles}</b></div><div class="stat"><span>Noise</span><b>${w.base.noise}</b></div><div class="toolbar"><button class="button-small open" data-file="data/weapons/weapons.json">Open JSON</button><button class="button-small open" data-file="assets/weapons/${w.id}.png">Open Texture</button></div></article>`).join('');document.querySelectorAll('.weapon-preview img').forEach(img=>img.onerror=()=>{const preview=img.closest('.weapon-preview');preview.classList.add('is-missing');const state=preview.querySelector('.asset-state');state.className='asset-state status-orange';state.textContent='PLACEHOLDER'});$('#components').innerHTML=cd.components.map(c=>`<article class="card"><div class="row"><h3>${c.display_name}</h3><code>${c.slot}</code></div><p>${c.tags.join(' · ')}</p><div class="stat"><span>Modifiers</span><b>${Object.keys(c.modifiers).length}</b></div></article>`).join('');document.querySelectorAll('.open').forEach(b=>b.onclick=()=>window.QC&&QC.ui.openFile(b.dataset.file))}catch(e){$('#weapons').textContent=e.message}}$('#reload').onclick=loadData;$('#open-game').onclick=()=>window.open('../index.html','_blank');init();
